/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package pers.qfy.struts.action;

//这是一个添加公告的action
//只负责添加公告
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import pers.qfy.dao.TbBbs;
import pers.qfy.dao.TbUser;
import pers.qfy.daotrue.TrueBBSDao;
import pers.qfy.daotrue.TrueUserDao;
import pers.qfy.struts.form.AddBBSForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-30-2016
 * 
 * XDoclet definition:
 * @struts.action path="/addBBS" name="addBBSForm" input="/form/addBBS.jsp" scope="request" validate="true"
 * @struts.action-forward name="error" path="addBBS"
 * @struts.action-forward name="success" path="showBBS" redirect="true"
 */
public class AddBBSAction extends Action {
	/*
	 * Generated Methods
	 */

	private TrueBBSDao dao;
	private HttpSession session;
	private TbBbs bbs;
	private TbUser user;
	
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		dao = new TrueBBSDao();
    	session = request.getSession();
    	user = (TbUser)session.getAttribute("user");
		
		AddBBSForm addBBSForm = (AddBBSForm) form;// TODO Auto-generated method stub
		String title = addBBSForm.getTitle();
		String content = addBBSForm.getContent();
		
		if ((title != null && !title.isEmpty()) &&
				(content != null && !content.isEmpty())) {
			return doAddBBS(mapping, request, response, title, content);
		}
		
		return mapping.findForward("input");
	}
	
	public ActionForward doAddBBS(ActionMapping mapping, HttpServletRequest request,
			HttpServletResponse response, String title, String content) {
		java.sql.Timestamp createtime = new java.sql.Timestamp(new java.util.Date().getTime());
		
		bbs = new TbBbs(title, content, user.getName(), createtime);
		
		int result = dao.addBBS(bbs);
    	if (result > 0) {
    		request.setAttribute("operater", "添加公告");
    		request.setAttribute("result", "成功");
    		return mapping.findForward("success");
    	} else {
    		request.setAttribute("operater", "添加公告");
    		request.setAttribute("result", "失败");
    		return mapping.findForward("error");
    	}
	}
}