/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package pers.qfy.struts.action;

import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import pers.qfy.dao.TbBbs;
import pers.qfy.dao.TbBbsDAO;
import pers.qfy.dao.TbUser;
import pers.qfy.daotrue.TrueBBSDao;
import pers.qfy.daotrue.TrueUserDao;
import pers.qfy.struts.form.AddBBSForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-30-2016
 * 
 * XDoclet definition:
 * @struts.action path="/addBBS" name="addBBSForm" input="/form/addBBS.jsp" scope="request" validate="true"
 * @struts.action-forward name="error" path="addBBS"
 * @struts.action-forward name="success" path="showBBS" redirect="true"
 */
public class ShowBBSAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	private TrueBBSDao dao;
	private HttpSession session;
	private TbBbs bbs;
	private TbUser user;
	private String currPage;
	private String id;
	
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		dao = new TrueBBSDao();
    	session = request.getSession();
    	user = (TbUser)session.getAttribute("user");
    	
    	currPage = request.getParameter("currPage");
		if(currPage==null || currPage=="")
		{
			currPage = "1";
		}
		
		id = request.getParameter("id");
		
		this.locale = this.getLocale(request);
		this.message = this.getResources(request);
		
		if (id == null) {
	    	String action = "showBBS.do?command=show";
	    	Map map = getPage(dao, "showBBSForm", action, Integer.parseInt(currPage), "select * from tb_bbs", dao.CLASSNAME);
	    	request.setAttribute("list", map.get("list"));
			request.setAttribute("pagingBar", map.get("bar"));
			
			return mapping.findForward("success");
		} else {
			if (id == "") {
				id = "1";
			}

			TbBbsDAO bbsDao = new TbBbsDAO();
			TbBbs bbs = bbsDao.findById(Integer.parseInt(id));
			request.setAttribute("bbs", bbs);
			return mapping.findForward("detail");
		}
	}
}